ALTER TABLE `farm`.`FormRules` ADD COLUMN `FNds` VARCHAR(20) CHARACTER SET cp1251 COLLATE cp1251_general_ci DEFAULT NULL COMMENT 'НДС' AFTER `TxtProducerCostEnd`,
 ADD COLUMN `TxtNdsBegin` INT(10) UNSIGNED DEFAULT NULL AFTER `FNds`,
 ADD COLUMN `TxtNdsEnd` INT(10) UNSIGNED DEFAULT NULL AFTER `TxtNdsBegin`;